ohtu-aikavali/aikavali-front

package-lock.json, package.json, src/app/components/common/AppBar.js, src/app/reducers/actions/uiActions.js, src/app/reducers/authReducer.js, src/index.js, src/tests/components/App/App.test.js, src/tests/components/common/AppBar.test.js, src/tests/reducers/actions/authActions.test.js, src/tests/reducers/actions/uiActions.test.js, src/tests/reducers/authReducer.test.js, src/tests/reducers/uiReducer.test.js
Reducer tests. Action tests. Component tests.
=> Tests for frontend

package.json, src/app/components/FrontPage/index.js, src/app/reducers/actions/exampleActions.js, src/app/reducers/actions/questionActions.js, src/app/reducers/constants/exampleConstants.js, src/app/reducers/constants/questionConstants.js, src/app/reducers/exampleReducer.js, src/app/reducers/index.js, src/app/reducers/questionReducer.js, src/app/services/exampleService.js, src/app/services/questionService.js
Fronttiin saa nyt kamaa backendistä. 
package.jsoniin laitoin siis proxy: 'http://localhost:3005', joten jos ajat backendiä koneella lokaalisti, tarvitsee backkarin .env tiedostossa olla määrittely port=3005
=> Backend integration

package-lock.json, package.json, src/app/components/FrontPage/index.js, src/app/components/Question/CompileQuestion.js, src/app/components/Question/PrintQuestion.js, src/app/components/Question/QuestionAnswer.js
Added material-ui for questions and answer (also created answer component). Added Print type question to index.js in FrontPage.
=> Material-ui for components

src/app/components/Admin/QuestionForm.js, src/app/components/FrontPage/index.js, src/app/components/Question/CompileQuestion.js, src/app/components/Question/PrintQuestion.js, src/app/components/Question/QuestionAnswer.js, src/app/components/Question/index.js, src/app/components/common/ButtonBar.js, src/app/reducers/actions/questionActions.js, src/app/reducers/constants/questionConstants.js, src/app/reducers/questionReducer.js, src/tests/components/Admin/QuestionForm.test.js, src/tests/components/FrontPage/index.test.js, src/tests/components/Question/CompileQuestion.test.js, src/tests/components/Question/PrintQuestion.test.js, src/tests/components/Question/Question.test.js, src/tests/components/Question/QuestionAnswer.test.js, src/tests/components/common/TemporaryDrawer.test.js, src/tests/reducers/questionReducer.test.js
Question logic is still kinda random. Needs some work, maybe just store selected answer to Question component's state instead of redux.
=> Refactored Question logic + some tests

src/app/components/FrontPage/index.js, src/app/components/Question/QuestionAnswer.js, src/app/components/Question/index.js, src/app/components/common/AlertWindow.js, src/app/components/common/ButtonBar.js, src/app/reducers/actions/gameActions.js, src/app/reducers/actions/questionActions.js, src/app/reducers/constants/gameConstants.js, src/app/reducers/constants/questionConstants.js, src/app/reducers/gameReducer.js, src/app/reducers/index.js, src/app/reducers/questionReducer.js, src/app/services/__mocks__/questionService.js, src/app/services/questionService.js, src/app/utilities/shuffleArray.js, src/index.css, src/tests/components/FrontPage/index.test.js, src/tests/components/Question/Question.test.js, src/tests/components/common/ButtonBar.test.js, src/tests/reducers/actions/questionActions.test.js, src/tests/reducers/questionReducer.test.js, src/tests/services/questionService.test.js
Kysymykset haetaan automaattisesti backendistä, kun ne ovat saatavilla (siis jos ne ovat jossain vaiheessa lopuneet). 
Kysymykseen kulutettu aika on tallessa, ja toiminnallisuus backendissä on ainoa mikä puuttuu.
=> PALJON KAIKKEE

src/app/components/Question/index.js, src/tests/reducers/actions/gameActions.test.js, src/tests/reducers/actions/questionActions.test.js, src/tests/reducers/gameReducer.test.js, src/tests/reducers/questionReducer.test.js
answerQuestionin parametreina lähetetään { id, value: 'Note: questionSkipped' }. Handlatkaa backissa näin.
=> Information about skipped question is sent to backend

.gitignore, src/app/services/__mocks__/authService.js, src/app/services/__mocks__/questionService.js, src/app/services/authService.js, src/app/utilities/__mocks__/userManager.js, src/tests/components/FrontPage/index.test.js, src/tests/reducers/actions/authActions.test.js, src/tests/reducers/actions/gameActions.test.js, src/tests/reducers/authReducer.test.js, src/tests/reducers/gameReducer.test.js, src/tests/services/authService.test.js
=> Testit toimii taas

package-lock.json, src/app/components/Question/CompileQuestion.js, src/app/components/Question/PrintQuestion.js, src/app/components/Question/QuestionAnswer.js, src/app/components/Question/index.js, src/app/components/common/DrawerList.js, src/tests/components/Question/QuestionAnswer.test.js
changes:
-After answering, clicking the correct answer fetches next question.
-Changed styles of additional answer options after correct answer is visible (cursor   & color).
-Fixed drawer ListItems
-Fixed tests
edit: fixed accidental text highlighting and mobile tap highlighting
edit2: fixed conflicts
=> questions styles and drawer fix

package-lock.json, src/app/components/Question/QuestionAnswer.js, src/tests/components/Question/QuestionAnswer.test.js
Kyssäreiden vastauksiin menee nyt monta riviä
=> Montarivia

package-lock.json, src/app/components/Admin/QuestionForm.js, src/app/components/Admin/index.js, src/app/reducers/actions/questionActions.js, src/app/services/questionService.js
Admin ui on integroitu bäkin kanssa. Koodi ei infoa käyttäjää mistään vielä muualla kuin konsolissa, mutta sen voi tehä myöhemmin
=> Admin UI on integroitu bäkkiin

package-lock.json, src/app/components/Question/index.js, src/app/components/common/ButtonBar.js
Link to the feedback Google form and changed Home icon to Profile icon in the ButtonBar.
=> Feedback link and profile to bottom navigation

package-lock.json, src/app/components/common/AppBar.js
Removed username (studentnumber) from the top right corner.
=> Removed username

package-lock.json, src/app/components/common/ButtonBar.js
Added navigation to the courses page to Buttonbar.js
=> Navigation to courses page

src/app/components/common/ButtonBar.js
Fixed the middle navigation button to be on the same level with other buttons.
=> Fixed navigation

src/app/components/common/ButtonBar.js
=> navigation

package-lock.json, package.json, src/app/components/Admin/QuestionForm.js, src/app/components/Question/CompileQuestion.js, src/app/components/Question/PrintQuestion.js, src/app/components/Question/index.js, src/tests/components/Question/CompileQuestion.test.js, src/tests/components/Question/PrintQuestion.test.js
Added feedback texts for right and wrong answers.
=> Feedback texts and form field help texts

package-lock.json, package.json, src/app/App.js, src/app/components/Admin/QuestionForm.js, src/app/components/Admin/admin.css, src/app/reducers/actions/questionActions.js, src/tests/components/Admin/QuestionForm.test.js
lisätty routeen /newquestion crowdsourcing ominaisuus. Vaatii toimiakseen että backkiin mergee pr "populate groups".
Route on avoin kaikille kirjautuneille mutta sinne ei vie vielä linkkiä muualta
=> Admin ui stepper

src/app/App.js, src/app/components/Admin/QuestionForm.js, src/app/components/Admin/index.js, src/app/components/common/ButtonBar.js
Add question button to bottom navigation, and Frontpage button to add question form.
=> Add question to bottom navigation

src/app/components/Admin/Popups/ConfirmPopup.js, src/app/components/Admin/Popups/SuccessPopup.js, src/app/components/Admin/Questions.js, src/app/components/Question/index.js, src/app/components/common/Popup.js, src/app/components/common/ReviewPopup.js, src/tests/components/common/ReviewPopup.test.js
Aika kämäset on vieläki, mut en ny jaksanu enempää perehtyä tuohon Transition komponenttiin.
=> Popupeille lisätty animaatiot

src/__mocks__/axios.js, src/app/services/__mocks__/authService.js, src/app/services/__mocks__/courseService.js, src/app/services/__mocks__/groupService.js, src/app/services/__mocks__/questionService.js, src/app/services/authService.js, src/app/services/courseService.js, src/tests/reducers/actions/authActions.test.js, src/tests/reducers/actions/courseActions.test.js, src/tests/reducers/actions/groupActions.test.js, src/tests/reducers/actions/questionActions.test.js, src/tests/reducers/courseReducer.test.js, src/tests/reducers/questionReducer.test.js, src/tests/services/authService.test.js, src/tests/services/courseService.test.js, src/tests/services/groupService.test.js, src/tests/services/questionService.test.js
Kaikki reducerit, actionit ja servicet on nyt testattu.
=> Added some tests, fixed some
